### ISSUE TITLE
Can't add validator using Polkadot 1KV Bot

### ISSUE THREAD

**Issue by Poggi-Luca** [helikon-labs/polkadot-kusama-1kv-telegram-bot#8]
Hello, I'm trying to re-add (removed for mistake) my Polkadot validator to the list.

I'm using the "/add" command, ask for validator stash, but after receiving the message "⏳ Fetching validator node data..." no more actions from bot side...

Could you kindly check?
Thank you

**Comment by mmagician** [comment]
Same issue here!
The Kusama one seems to work well though

**Comment by kukabi** [comment]
Thanks for the report @mmagician & @Poggi-Luca! I’ll check and fix it in a bit 👍🏼

**Comment by Poggi-Luca** [comment]
@kukabi solved! Thank you

**Comment by mmagician** [comment]
Working for me too! Amazing
