### ISSUE TITLE
Support for non-1kv validators

### ISSUE THREAD

**Issue by mmagician** [helikon-labs/polkadot-kusama-1kv-telegram-bot#9]
I really love the bot for 1kv! Are there any plans to support non-1kv validators for Polkadot & Kusama?
In case you are interested in extending the bot, we could support its development via the [Web3 Grants Program](https://github.com/w3f/Grants-Program). I'm a member of the grants team and so if you need support in submitting the application let me know - though I hope our READMEs should be pretty self-explanatory :)

**Comment by kukabi** [comment]
Hi @mmagician, thanks so much, I'm happy it's useful to you:) Yeah I'd really like to improve it to support all validators. I may have a few questions regarding the grant, could you please share your Matrix handle or ping me @ `helikon:matrix.org`? Thanks!

PS. I've also been planning to add support for:

- Para-validation info.
- Rank details, history and breakdown (like the spider chart on the Kusama 1KV site).
- Nomination details (nominator addresses and amounts).
- Notification for when a validator loses a nomination.

Please let me know if you'd have further feature requests.

**Comment by kukabi** [comment]
Migration complete!
Proposal: https://github.com/w3f/Grants-Program/blob/master/applications/subvt-telegram-bot.md
Repository: https://github.com/helikon-labs/subvt-backend/tree/development/subvt-telegram-bot
